#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------
cd base
./Allclean
cd ..

rm -rf translate_x_1
rm -rf rotate-angle
rm -rf scale
#------------------------------------------------------------------------------
